kanisa/models/blog.py
from autoslug import AutoSlugField
from datetime import date, timedelta
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models


class PublishedPostManager(models.Manager):
    def get_queryset(self):
        return super(
            PublishedPostManager,
            self).get_queryset().filter(
                publish_date__lte=date.today()
            )


class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from='title', unique=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
    publish_date = models.DateField(
        help_text=('Blog posts are published on the site at 00:00 on the '
                   'publish date.')
    )
    updated_date = models.DateTimeField(auto_now=True)
    teaser_text = models.TextField(
        verbose_name='Teaser',
        help_text=('This should normally be the first few sentences of your '
                   'post.')
    )
    main_text = models.TextField(
        verbose_name='Main text',
        help_text=('This should be the bulk of your post, and will follow on '
                   'from what\'s in the teaser.')
    )
    enable_comments = models.BooleanField(
        default=True,
        help_text=('Comments are automatically closed 30 days after the blog '
                   'post is published.')
    )

    objects = models.Manager()
    published_objects = PublishedPostManager()

    def __unicode__(self):
        return self.title

    def published(self):
        return self.publish_date <= date.today()

    def full_text(self):
        return self.teaser_text + '\n\n' + self.main_text

    def get_absolute_url(self):
        return reverse(
            'kanisa_public_blog_detail',
            args=[self.publish_date.year, self.slug, ]
        )

    def comments_allowed(self):
        if not self.enable_comments:
            return False

        if not self.published():
            return False

        if self.publish_date + timedelta(days=30) < date.today():
            return False

        return True

    class Meta:
        # Need this because I've split up models.py into multiple
        # files.
        app_label = 'kanisa'
        ordering = ['-publish_date', '-pk']
        permissions = (
            ('manage_blog',
             'Can manage your blog posts'),
        )


class BlogComment(models.Model):
    post = models.ForeignKey(BlogPost)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
    body = models.TextField(verbose_name='Comment')
    publish_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        # Need this because I've split up models.py into multiple
        # files.
        app_label = 'kanisa'
        ordering = ['publish_date', 'pk']

    def __unicode__(self):
        return 'Comment on %s' % self.post

kanisa/urls/management/__init__.py
from django.conf.urls import patterns, include, url
from kanisa.views.management import KanisaManagementIndexView


urlpatterns = patterns(
    '',
    url(r'^$', KanisaManagementIndexView.as_view(), {}, 'kanisa_manage_index'),
    url(r'^banners/', include('kanisa.urls.management.banners')),
    url(r'^blocks/', include('kanisa.urls.management.blocks')),
    url(r'^blog/', include('kanisa.urls.management.blog')),
    url(r'^branding/', include('kanisa.urls.management.branding')),
    url(r'^diary/', include('kanisa.urls.management.diary')),
    url(r'^documents/', include('kanisa.urls.management.documents')),
    url(r'^media/', include('kanisa.urls.management.media')),
    url(r'^navigation/', include('kanisa.urls.management.navigation')),
    url(r'^pages/', include('kanisa.urls.management.pages')),
    url(r'^sermons/', include('kanisa.urls.management.sermons')),
    url(r'^users/', include('kanisa.urls.management.users')),
    url(r'^xhr/', include('kanisa.urls.management.xhr')),
)

kanisa/urls/management/xhr/__init__.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns(
    '',
    url(r'^diary/', include('kanisa.urls.management.xhr.diary')),
    url(r'^media/', include('kanisa.urls.management.xhr.media')),
    url(r'^navigation/', include('kanisa.urls.management.xhr.navigation')),
    url(r'^pages/', include('kanisa.urls.management.xhr.pages')),
    url(r'^sermons/', include('kanisa.urls.management.xhr.sermons')),
)

kanisa/views/management/__init__.py
from django.contrib.auth import get_user_model
from kanisa.views.generic import (
    KanisaAnyAuthorizationMixin,
    KanisaTemplateView
)


class KanisaManagementIndexView(KanisaAnyAuthorizationMixin,
                                KanisaTemplateView):
    template_name = 'kanisa/management/index.html'

    def get_context_data(self, **kwargs):
        context = super(KanisaManagementIndexView,
                        self).get_context_data(**kwargs)

        users = get_user_model().objects.all()
        context['user_list'] = users.order_by('-last_login')[:5]

        return context

kanisa/templates/kanisa/management/pages/_page_table.html
{% if page_list %}
<table class="table table-striped kanisa_diary">
  <thead>
    <tr>
      <th>Title</th>
      <th class="iconcell"></th>
      <th>Published</th>
      <th>Modified</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for page in page_list %}
    <tr>
      <td>
        <span style="display: inline-block; width: {{ page.get_level }}em"></span>
        {% if page.get_level != 0 %}&#8627;{% endif %}
        <a href="{% url 'kanisa_manage_pages_update' page.pk %}">
          {{ page.title }}
        </a>
      </td>
      <td class="iconcell">
        <a href="{% url 'kanisa_manage_pages_create' %}?parent={{ page.pk }}" title="Create a page with &ldquo;{{ page.title }}&rdquo; as its parent">
          <i class="glyphicon glyphicon-plus-sign"></i>
        </a>
      </td>
      <td class="iconcell">
        {% if not page.draft %}
        <i class="glyphicon glyphicon-ok" title="This page is published"></i>
        {% else %}
        <i class="glyphicon glyphicon-remove" title="This page is not published"></i>
        {% endif %}
      </td>
      <td>
        <abbr title="{{ page.modified|date:"r"}}">
          {{ page.modified|timesince }} ago
        </abbr>
      </td>
      <td>
        {% if page.is_leaf_node %}
        <a class="btn btn-danger btn-xs page_delete" href="{% url 'kanisa_manage_pages_delete' page.pk %}" data-page-title="{{ page.title }}">
          Delete
        </a>
        {% endif %}
      </td>
      <td class="iconcell">
        {% if not page.draft %}
        <a href="/{{ page.get_path }}" title="View on site"><i class="glyphicon glyphicon-eye-open"></i></a>
        {% endif %}
      </td>
    </tr>
    {% endfor %}
</tbody>
</table>
{% else %}
<div class="alert alert-warning">
There are no pages to display.
</div>
{% endif %}

kanisa/templates/kanisa/management/pages/_parent_select_options.html
{% load kanisa_tags %}

<option value="">---------</option>

{% for page in page_list %}
<option value="{{ page.pk }}">{% for i in page.level|get_range %}---{% endfor %} {{ page.title }}</option>
{% endfor %}

kanisa/templates/kanisa/management/pages/_quick_creation.html
<h3>Quick Create
  <span class="help_text">(Want to use the <a href="{% url 'kanisa_manage_pages_create' %}">full page creation form</a>?)</span>
</h3>

<form class="form-inline" method="post" action="{% url 'kanisa_manage_pages_create' %}" id="page_quick_create">
  <div class="form-group">
  {% csrf_token %}
  <input type="text" name="title" id="id_title" placeholder="Title" class="form-control" />
  <select name="parent" id="id_parent" class="form-control">
    {% include 'kanisa/management/pages/_parent_select_options.html' %}
  </select>
  <button type="submit" class="btn btn-success">Submit</button>
  <div class="inline-status"></div>
  </div>
</form>

kanisa/templates/kanisa/management/pages/index.html
{% extends 'kanisa/management/base.html' %}

{% block extrajs %}
<script type="text/javascript">
var page_create_url = "{% url 'kanisa_manage_xhr_create_page' %}";
var pages_list_url = "{% url 'kanisa_manage_xhr_list_pages' %}";
</script>
{% endblock %}

{% block content %}

{% include 'kanisa/management/pages/_quick_creation.html' %}
<hr />

<div id="page_details_container">
{% include 'kanisa/management/pages/_page_table.html' %}
</div>

{% endblock %}