kanisa/models/documents.py
from autoslug import AutoSlugField
from django.core.urlresolvers import reverse
from django.db import models
import os


KNOWN_EXTENSIONS = {
    '.doc': 'Word Document',
    '.docx': 'Word Document',
    '.pdf': 'PDF',
    '.xls': 'Excel Document',
    '.xlxs': 'Excel Document',
}


class Document(models.Model):
    title = models.CharField(max_length=60,
                             help_text='The name of the document.')
    slug = AutoSlugField(populate_from='title', unique=True)
    file = models.FileField(upload_to='kanisa/documents')
    details = models.TextField(blank=True,
                               null=True,
                               help_text=('Give a brief idea of what\'s in '
                                          'this document.'))
    public = models.BooleanField(default=True,
                                 help_text=('If checked, this document can be '
                                            'added as an attachment to '
                                            'publicly accessible areas of '
                                            'your site.'))
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    downloads = models.IntegerField(default=0,
                                    editable=False)

    def __unicode__(self):
        return self.title

    def file_name(self):
        return os.path.basename(self.file.name)

    def extension_description(self):
        prefix, extension = os.path.splitext(self.file.name)

        extension = extension.lower()

        if extension in KNOWN_EXTENSIONS:
            return KNOWN_EXTENSIONS[extension]

        return extension

    def download_url(self):
        return reverse('kanisa_members_documents_download', args=[self.pk, ])

    class Meta:
        # Need this because I've split up models.py into multiple
        # files.
        app_label = 'kanisa'
        ordering = ('-created', )
        permissions = (
            ('manage_documents',
             'Can manage your documents'),
        )

kanisa/forms/documents.py
from kanisa.forms import KanisaBaseModelForm
from kanisa.forms.widgets import KanisaMainInputWidget
from kanisa.models import Document


class DocumentForm(KanisaBaseModelForm):
    class Meta:
        model = Document
        widgets = {'details': KanisaMainInputWidget(), }


class DocumentFormSimple(KanisaBaseModelForm):
    class Meta:
        model = Document
        exclude = ('details', 'public', )

kanisa/urls/members/__init__.py
from django.conf.urls import include, patterns, url
import kanisa.views.members as base


urlpatterns = patterns(
    '',
    url(r'^$', base.index, {}, 'kanisa_members_index'),
    url(r'^account/', include('kanisa.urls.members.account')),
    url(r'^documents/', include('kanisa.urls.members.documents')),
    url(r'^services/', include('kanisa.urls.members.services')),
)

kanisa/urls/members/account/__init__.py
from django.conf.urls import include, patterns, url
from kanisa.views.members.account import (
    KanisaAccountModificationView,
    KanisaLoginView,
    KanisaRegistrationView,
    KanisaRegistrationThanksView
)


urlpatterns = patterns(
    '',
    url(r'^login/$', KanisaLoginView.as_view(), {},
        'kanisa_members_login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'template_name': 'kanisa/auth/logout.html', },
        'kanisa_members_logout'),

    url(r'^modify/$', KanisaAccountModificationView.as_view(), {},
        'kanisa_members_account_modify'),

    url(r'^registration/$', KanisaRegistrationView.as_view(), {},
        'kanisa_members_registration'),
    url(r'^registration/thanks/$', KanisaRegistrationThanksView.as_view(), {},
        'kanisa_members_registration_thanks'),

    url(r'^auth/', include('kanisa.urls.members.account.password')),
)

kanisa/urls/members/services/__init__.py
from django.conf.urls import include, patterns, url
import kanisa.views.members.services as views


urlpatterns = patterns(
    '',
    url(r'^$', views.index, {'show_all': False},
        'kanisa_members_services_index'),
    url(r'^all/$', views.index, {'show_all': True},
        'kanisa_members_services_index_all'),

    url(r'^bands/', include('kanisa.urls.members.services.bands')),
    url(r'^ccli/', include('kanisa.urls.members.services.ccli')),
    url(r'^composers/', include('kanisa.urls.members.services.composers')),
    url(r'^service/', include('kanisa.urls.members.services.service')),
    url(r'^songs/', include('kanisa.urls.members.services.songs')),
)

kanisa/views/members/__init__.py
from django.views.generic.base import TemplateView
from kanisa.models import Document, Service
from kanisa.views.members.auth import MembersBaseView


class MembersIndexView(MembersBaseView, TemplateView):
    template_name = 'kanisa/members/index.html'

    def get_context_data(self, **kwargs):
        context = super(MembersIndexView,
                        self).get_context_data(**kwargs)

        context['documents'] = Document.objects.all()[:5]

        if self.request.user.can_see_service_plans():
            context['services'] = Service.future_objects.all()[:5]
        else:
            context['services'] = None

        return context
index = MembersIndexView.as_view()

kanisa/views/members/account/__init__.py
import urlparse
from django.contrib.auth import (
    get_user_model,
    login,
    REDIRECT_FIELD_NAME
)
from django.contrib.sites.models import RequestSite
from django.core.cache import cache
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponseRedirect, Http404
from django.views.generic.edit import FormView, CreateView
from kanisa import conf
from kanisa.forms.auth import (
    KanisaAccountModificationForm,
    KanisaLoginForm,
    KanisaAccountCreationForm,
)
from kanisa.utils.auth import has_any_kanisa_permission, users_with_perm
from kanisa.utils.mail import send_bulk_mail
from kanisa.views.generic import (
    KanisaTemplateView,
    KanisaUpdateView
)
from kanisa.views.members.auth import MembersBaseView


class KanisaLoginView(FormView):
    template_name = 'kanisa/auth/login.html'
    form_class = KanisaLoginForm
    success_url = reverse_lazy('kanisa_manage_index')

    def get_success_url(self, user):
        if has_any_kanisa_permission(user):
            return self.success_url

        return reverse('kanisa_members_index')

    def form_valid(self, form):
        redirect_to = self.request.REQUEST.get(REDIRECT_FIELD_NAME, '')
        netloc = urlparse.urlparse(redirect_to)[1]

        # Use default setting if redirect_to is empty
        if not redirect_to:
            redirect_to = self.get_success_url(form.get_user())

        # Heavier security check -- don't allow redirection to a
        # different host.
        elif netloc and netloc != self.request.get_host():
            redirect_to = self.get_success_url(form.get_user())

        # Okay, security checks complete. Log the user in.
        login(self.request, form.get_user())
        return HttpResponseRedirect(redirect_to)


class KanisaAccountModificationView(MembersBaseView,
                                    KanisaUpdateView):
    template_name = 'kanisa/auth/account.html'
    form_class = KanisaAccountModificationForm
    success_url = reverse_lazy('kanisa_members_index')
    model = get_user_model()
    kanisa_title = 'Update your account'

    def get_object(self):
        return self.request.user

    def get_message(self, form):
        return 'Changes saved.'


class KanisaRegistrationMixin(object):
    def dispatch(self, request, *args, **kwargs):
        if not conf.KANISA_REGISTRATION_ALLOWED:
            raise Http404

        return super(KanisaRegistrationMixin,
                     self).dispatch(request, *args, **kwargs)


class KanisaRegistrationView(KanisaRegistrationMixin, CreateView):
    template_name = 'kanisa/auth/registration.html'
    form_class = KanisaAccountCreationForm
    success_url = reverse_lazy('kanisa_members_registration_thanks')

    def form_valid(self, form):
        rval = super(KanisaRegistrationView, self).form_valid(form)

        cache.delete('kanisa_inactive_users')

        send_bulk_mail(users_with_perm('manage_users'),
                       'on_account_registration',
                       {'user': form.instance,
                        'site': RequestSite(self.request), })

        return rval


class KanisaRegistrationThanksView(KanisaRegistrationMixin,
                                   KanisaTemplateView):
    kanisa_title = 'Registration Complete'
    template_name = 'kanisa/auth/registration_thanks.html'

kanisa/views/members/auth.py
from kanisa.views.generic import KanisaAuthorizationMixin


class MembersBaseView(KanisaAuthorizationMixin):
    def authorization_check(self, user):
        return user.is_active

kanisa/views/members/services/__init__.py
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import get_object_or_404
from kanisa.models import (
    Band,
    Service,
)
from kanisa.utils.services import most_popular_songs
from kanisa.views.generic import (
    KanisaAuthorizationMixin,
    KanisaListView,
)


class ServiceBaseView(KanisaAuthorizationMixin):
    kanisa_root_crumb = {
        'text': 'Services',
        'url': reverse_lazy('kanisa_members_services_index')
    }

    def authorization_check(self, user):
        if not user.is_active:
            return False

        return user.can_see_service_plans()


class ServiceRestrictedBaseView(KanisaAuthorizationMixin):
    kanisa_root_crumb = {'text': 'Services',
                         'url': reverse_lazy('kanisa_members_services_index')}
    permission = 'kanisa.manage_services'


class ServiceIndexView(ServiceBaseView, KanisaListView):
    template_name = 'kanisa/members/services/index.html'
    kanisa_title = 'Service Planning'
    kanisa_is_root_view = True
    paginate_by = 20

    def get_queryset(self):
        if self.kwargs['show_all']:
            qs = Service.objects.all()
        else:
            qs = Service.future_objects.all()

        return qs.order_by('-event__date')

    def get_context_data(self, **kwargs):
        context = super(ServiceIndexView,
                        self).get_context_data(**kwargs)
        context['showing_all'] = self.kwargs['show_all']
        context['top_five_songs'] = most_popular_songs()[:5]
        context['bands'] = Band.objects.all()

        musician_services = self.request.user.service_musicians.all()
        leader_services = self.request.user.service_set.all()

        all_service_pks = set(
            [s.pk for s in musician_services] +
            [s.pk for s in leader_services]
        )

        for service in context['service_list']:
            service.user_is_involved = service.pk in all_service_pks

        active = [s.user_is_involved for s in context['service_list']]
        context['active_in_some_services'] = any(active)

        return context
index = ServiceIndexView.as_view()


class BaseServiceManagementView(ServiceRestrictedBaseView):
    @property
    def service(self):
        if not hasattr(self, "service_"):
            pk = int(self.kwargs['service_pk'])
            self.service_ = get_object_or_404(Service, pk=pk)

        return self.service_

kanisa/templates/kanisa/members/_breadcrumbs.html
<ul class="breadcrumb">
  {% block breadcrumbs %}
  <li>
    <a href="{% url 'kanisa_members_index' %}">Members' Home</a>
  </li>
  {% if kanisa_root_crumb %}
  <li>
    {% if not kanisa_is_root_view %}
    <a href="{{ kanisa_root_crumb.url }}">{{ kanisa_root_crumb.text }}</a>
    {% else %}
    {{ kanisa_root_crumb.text }}
    {% endif %}
  </li>
  {% endif %}

  {% for crumb in kanisa_intermediate_crumbs %}
  <li>
    <a href="{{ crumb.url }}">
    {{ crumb.title }}
    </a>
  </li>
  {% endfor %}

  {% if kanisa_title and not kanisa_is_root_view %}
  <li>
     {{ kanisa_title }}
  </li>
{% endif %}
{% endblock %}
</ul>

kanisa/templates/kanisa/members/_document_table.html
{% load kanisa_markup %}

<table class="table table-striped kanisa_diary">
  <thead>
    <tr>
      <th>Title</th>
      <th>Uploaded</th>
      <th>Modified</th>
    </tr>
  </thead>
  <tbody>
    {% for document in document_list %}
    <tr>
      <td>
        <strong>
          <a href="{{ document.download_url }}">{{ document.title }}</a>
        </strong>
        ({% if document.extension_description %}{{ document.extension_description }}, {% endif %}{{ document.file.size|filesizeformat }})
        {% if document.details %}
        <div class="document_details_short">
          {{ document.details|kanisa_markdown|striptags|truncatewords_html:20 }}
          <span class="text-muted">(Click to expand)</span>
        </div>
        <div class="document_details_full" style="display:none">
          {{ document.details|kanisa_markdown }}
        </div>
        {% endif %}
      </td>
      <td style="vertical-align: top; width:12em">
        <abbr title="{{ document.created|date:"r"}}">
          {{ document.created|timesince }} ago
        </abbr>
      </td>
      <td style="vertical-align: top; width:12em">
        <abbr title="{{ document.modified|date:"r"}}">
          {{ document.modified|timesince }} ago
        </abbr>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% include "kanisa/_simple_pagination.html" %}

kanisa/templates/kanisa/members/_sidebar.html
{% load kanisa_tags %}

<ul class="nav nav-stacked sidebar">
  <li>
    <a href="{% url 'kanisa_members_index' %}">
      <i class="glyphicon glyphicon-home"></i>
      Home
    </a>
  </li>
  <li>
    <a href="{% url 'kanisa_members_password_change' %}">
      <i class="glyphicon glyphicon-lock"></i>
      Change Password
    </a>
  </li>
  <li>
    <a href="{% url 'kanisa_members_account_modify' %}">
      <i class="glyphicon glyphicon-user"></i>
      Update Account
    </a>
  </li>
  <li>
    <a href="{% url 'kanisa_members_documents' %}">
      <i class="glyphicon glyphicon-file"></i>
      Documents
    </a>
  </li>
  {% if user.can_see_service_plans %}
    <li>
      <a href="{% url 'kanisa_members_services_index' %}">
        <i class="glyphicon glyphicon-bullhorn"></i>
        Service Planning
      </a>
    </li>
  {% endif %}
</ul>

{% include "kanisa/_profile_sidebar.html" %}

{% kanisa_is_permissioned_user as is_permissioned %}
{% if is_permissioned %}
  <hr />
  <ul class="nav nav-stacked sidebar">
    <li>
      <a href="{% url 'kanisa_manage_index' %}">
        <i class="glyphicon glyphicon-cog"></i>
        Site Management
      </a>
    </li>
  </ul>
{% endif %}

kanisa/templates/kanisa/members/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include "kanisa/_head.html" %}
    {% block extrajs %}
    <link rel="stylesheet" type="text/css" media="all" href="{% static 'kanisa/vendor/chosen-1.0.0/chosen.min.css' %}" />
    <script src="{% static 'kanisa/vendor/chosen-1.0.0/chosen.jquery.min.js' %}"></script>
    {% include "kanisa/management/_js.html" %}
    {% endblock %}
  </head>
  <body>

    <div class="container">
      {% include "kanisa/_logo.html" %}
      {% include "kanisa/_header.html" %}

      {% block precontent %}
      {% endblock %}

      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
          {% include 'kanisa/members/_sidebar.html' %}
          {% endblock %}
        </div>

        <div class="col-md-10">
          {% include 'kanisa/members/_breadcrumbs.html' %}
          {% include 'kanisa/_alerts.html' %}
          <h1>
            {% block pagetitle %}
            {% if kanisa_title %}
            {{ kanisa_title }}
            {% else %}
            Hello!
            {% endif %}
            {% endblock %}
          </h1>

          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

kanisa/templates/kanisa/members/delete.html
{% extends 'kanisa/members/base.html' %}

{% block content %}

<p class="lead">{{ kanisa_delete_confirm }}</p>

{% if kanisa_delete_extra %}
  <p class="lead text-muted">{{ kanisa_delete_extra }}</p>
{% endif %}

<form method="post" action="">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="{{ kanisa_delete_button }}" />
    <a class="btn btn-default" href="{{ kanisa_cancel_url }}">No, go back</a>
</form>

{% endblock %}

kanisa/templates/kanisa/members/documents.html
{% extends 'kanisa/members/base.html' %}

{% block content %}

  {% if document_list %}
    {% include 'kanisa/members/_document_table.html' %}
  {% else %}
    <div class="alert alert-warning">
      There are no documents to display.
    </div>
  {% endif %}

  {% if perms.kanisa.manage_documents %}
    <p>
      <a href="{% url 'kanisa_manage_documents_create' %}" class="btn btn-lg btn-success">
        <i class="glyphicon glyphicon-plus"></i>
        Upload a Document
      </a>
    </p>
  {% endif %}

{% endblock %}

kanisa/templates/kanisa/members/form.html
{% extends 'kanisa/members/base.html' %}

{% block content %}
{% include 'kanisa/management/_form.html' %}
{% endblock %}

kanisa/templates/kanisa/members/index.html
{% extends 'kanisa/members/base.html' %}

{% load kanisa_homepage %}
{% load kanisa_tags %}

{% block pagetitle %}
<h1>Members&rsquo; Area</h1>
{% endblock %}

{% block content %}

<div class="lead">
  {% kanisa_content_block 'members_welcome' %}
</div>

<p>
  You are logged in as <strong>{{ user.get_display_name }}</strong>.
  {% if user.email %}
  Your registered email address is <strong>{{ user.email }}</strong>.
  {% else %}
  We do not have an email address registered for you.
  {% endif %}
</p>

<hr />

<div class="row">
  <div class="col-md-6">
    <h3>Recent Documents</h3>
    <table class="table table-striped kanisa_diary">
      <tbody>
        {% for document in documents %}
        <tr>
          <td>
            <strong>
              <a href="{{ document.download_url }}">{{ document.title }}</a>
            </strong>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <p>Looking for <a href="{% url 'kanisa_members_documents' %}">other documents</a>?</p>
  </div>
  {% if user.can_see_service_plans %}
  <div class="col-md-6">
    <h3>Upcoming Services</h3>
    {% if services %}
    {% else %}
    <p class="alert alert-info">
      There are no services in the diary at present.
    </p>
    {% endif %}

    <p>View <a href="{% url 'kanisa_members_services_index' %}">more service plans</a>.</p>
  </div>
  {% endif %}
</div>

{% kanisa_is_permissioned_user as is_permissioned %}
{% if is_permissioned %}
<hr />

<p class="text-muted">
  Looking for the
  <a href="{% url 'kanisa_manage_index' %}">site management area</a>?
</p>
{% endif %}

{% endblock %}